codio/site

- source/stylesheets/partials/_header.scss
For https://codio.myjetbrains.com/youtrack/issue/codio-4921
> fixed gravatar style

- source/partials/_pricing-education.erb
- source/partials/_pricing-professional.erb
issue #codio-4589. 
https://codio.myjetbrains.com/youtrack/issue/codio-4589
> Send plan id to account billing.

- source/javascripts/partials/_codio.coffee
issue #codio-5394. 
https://codio.myjetbrains.com/youtrack/issue/codio-5394
> set user-edu cookie if got url param.

- source/about.html.erb
- source/stylesheets/all-new.scss
- source/stylesheets/new/_about.scss
- source/stylesheets/new/_utils.scss
Add style for team descriptions as described in the issue 5489:
https://codio.myjetbrains.com/youtrack/issue/codio-5484
> 5489 team descriptions

- source/stylesheets/new/_blog.scss
Fix blog-header a:hover has "text-decoration: underline" in single post view
> Style(blog): fix a:hover on blog-header while looking at a post

- source/about.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-5599
> Teams: fix long descriptions to correctly fit in Firefox

- source/javascripts/partials/_codio.es6.erb
https://codio.myjetbrains.com/youtrack/issue/codio-6080
> Store a referrer to the cookie.

- source/stylesheets/_code.scss.erb
- source/stylesheets/pages/_docs.scss
- source/stylesheets/pages/_index.scss
- source/stylesheets/pages/_legal.scss
https://developer.mozilla.org/ru/docs/Web/CSS/initial
For https://codio.myjetbrains.com/youtrack/issue/codio-6476
> Fixed styles for IE (IE doesn't support initial css keyword)

- source/javascripts/partials/_slider.es6
- source/layouts/layout.erb
- source/partials/_call-to-action.erb
- source/partials/_header.erb
- source/partials/_nav.erb
- source/university.html.erb
> [university] Select university pricing in the ca

- source/docs/dashboard/browser-support.html.md
https://codio.myjetbrains.com/youtrack/issue/codio-6559
> Docs(dashboard/browser-support): add description for IE compatibility view

- source/stylesheets/_code.scss.erb
https://codio.myjetbrains.com/youtrack/issue/codio-6494#
> Fix pre scrollbar for code elements in FF.

- source/docs/dashboard/organizations/create.html.md
- source/docs/dashboard/organizations/education.html.md
Ref issue: https://codio.myjetbrains.com/youtrack/issue/codio-6715
> Docs(dashboard): show the correct number of users for eduTrial

- config.rb
- source/stylesheets/_variables.scss
- source/stylesheets/pages/_index.scss
- source/stylesheets/pages/_school.scss
- source/stylesheets/pages/_university.scss
- source/university.html.erb
university part
https://codio.myjetbrains.com/youtrack/issue/codio-6691
> Change university landing page.

- source/javascripts/partials/_analytics.es6
- source/javascripts/partials/_demo.es6
https://codio.myjetbrains.com/youtrack/issue/codio-7086
> Move book a demo tracking to a process finishes successeful

- source/partials/_head.erb
https://codio.myjetbrains.com/youtrack/issue/codio-6674
> Added FB Pixel code

- source/features/management.html.erb
- source/stylesheets/pages/features/_shared.scss
https://codio.myjetbrains.com/youtrack/issue/codio-7126
> Update features/management page + fix for button

- source/partials/vendors/_google-analytics.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7254#
> Fix ga tracking

- source/demo.html.erb
- source/features/content-authoring.html.erb
- source/features/ide.html.erb
- source/features/index.html.erb
- source/features/infrastructure.html.erb
- source/features/management.html.erb
- source/features/templates.html.erb
- source/partials/_head.erb
- source/pricing.html.erb
- source/university.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7247
> Updated titles and descriptions for some pages

- source/demo.html.erb
- source/partials/_head.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7293
> Updated tracking code

- Gemfile
- Gemfile.lock
- config.rb
- source/docs/index.html.erb
- source/javascripts/all.js
- source/stylesheets/_bootstrap_codio.scss
- source/stylesheets/_variables.scss
- source/stylesheets/all.css.scss
- source/stylesheets/pages/_docs.scss
Collapse/expand & hyperlinks.
https://codio.myjetbrains.com/youtrack/issue/codio-7397.
> 7397 docs getting started

- source/javascripts/partials/_docs.es6
- source/javascripts/partials/_local_storage.es6
https://codio.myjetbrains.com/youtrack/issue/codio-7452#tab=Comments
> Doc tabs priority

- source/docs/acount.html.erb
- source/docs/index.html.erb
- source/docs/search.html.erb
- source/docs/started.html.erb
- source/javascripts/partials/_docs.es6
- source/stylesheets/pages/_docs.scss
https://codio.myjetbrains.com/youtrack/issue/codio-7474#
> Fix swifttype search

- source/school.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7466#
> Update webinar link.

- source/index.html.erb
- source/stylesheets/pages/_index.scss
https://codio.myjetbrains.com/youtrack/issue/codio-7507#
> Fix testimonials page look for mobile.

- source/school.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7534
> 7534 wrong link.

- source/stylesheets/pages/_university.scss
- source/stylesheets/pages/features/_index.scss
https://codio.myjetbrains.com/youtrack/issue/codio-7515
> 7515 features looks incorrect

- source/javascripts/partials/_legal.es6
- source/partials/_footer.erb
- source/stylesheets/partials/_legal-side-navigation.scss
https://codio.myjetbrains.com/youtrack/issue/codio-7522
> 7522 Fixed display Legal Stuff on mobil screens.

- source/legal/privacy.html.md
- source/legal/terms.html.md
- source/partials/_structured-markup.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7570
> 7570 update registered address details

- source/javascripts/partials/_pricing.es6
https://codio.myjetbrains.com/youtrack/issue/codio-7591#
> IE pricing page fix

- config.rb
- source/layouts/layout.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7535
> Cookie consent.

- source/features/curriculum.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7664
> 7664 small typo on key features page

- Gemfile.lock
- source/stylesheets/pages/_university.scss
- source/university.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7655
> 7655 Update University page with new video

- Gemfile.lock
- data/prices.yml
- source/javascripts/partials/_pricing.es6
https://codio.myjetbrains.com/youtrack/issue/codio-7666
> 7666 update to pricing page

- source/javascripts/partials/_pricing.es6
- source/pricing.html.erb
- source/stylesheets/pages/_pricing.scss
https://codio.myjetbrains.com/youtrack/issue/codio-7676
> 7676 Add VAT to pricing page

- source/stylesheets/pages/_legal.scss
- source/stylesheets/partials/_legal-side-navigation.scss
https://codio.myjetbrains.com/youtrack/issue/codio-7674
> 7674 site legal pages top part is hidden

- Gemfile.lock
- source/features/ide.html.erb
- source/stylesheets/pages/features/_ide.scss
https://codio.myjetbrains.com/youtrack/issue/codio-7622
> 7622 Update to Web IDE pages

- source/index.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7914
> 7914 Updated text and link on homepage banner.

- source/demo.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7926
> 7926 Change top text copy on the codio.com/demo

- source/school.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7931
> 7931 Fix type on www.codio.com/school

- source/partials/_nav.erb
- source/school.html.erb
- source/stylesheets/pages/_school.scss
https://codio.myjetbrains.com/youtrack/issue/codio-7916
> 7916 update homepage with demo buttons

- source/about/index.html.erb
- source/about/mission.html.erb
- source/docs/index.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7517
> 7517 seo ensure www.codio.com site is recognised by google as mobile friendly

- source/javascripts/partials/_pricing.es6
- source/pricing.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7845
> 7845 Remove GBP pricing from Individual Tab page

- source/partials/_head.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7799
> Added meta tags support for site per page.

- source/partials/_docs-side-navigation.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8083
> 8803 Styling breaks down some points

- source/about/index.html.erb
- source/about/mission.html.erb
- source/demo.html.erb
- source/developer.html.erb
- source/features/curriculum.html.erb
- source/features/ide.html.erb
- source/index.html.erb
- source/javascripts/partials/_pricing.es6
- source/partials/_footer.erb
- source/partials/_header.erb
- source/school.html.erb
- source/university.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-7814
> 7814 seo images with no alt tag

- source/index.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8155
> 8155 Quick change to text on Homepage banner

- source/index.html.erb
- source/javascripts/partials/_pricing.es6
https://codio.myjetbrains.com/youtrack/issue/codio-8188
> 8188 quick text change to banner on homepage

- source/docs/started.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8207
> use one column for get sarted page

- source/demo.html.erb
- source/javascripts/partials/_demo.es6
- source/stylesheets/pages/_demo.scss
https://codio.myjetbrains.com/youtrack/issue/codio-8209
> 8209 request a demo page fixing

- source/docs/index.html.erb
- source/docs/settings.html.erb
- source/docs/started.html.erb
- source/javascripts/partials/_docs.es6
- source/partials/docs/_actions.html.erb
- source/stylesheets/pages/_docs.scss
https://codio.myjetbrains.com/youtrack/issue/codio-8139
> 8139 search field in the docs

- source/index.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8299
> 8299 Quick text change to homepage banner

- source/index.html.erb
- source/stylesheets/pages/_index.scss
https://codio.myjetbrains.com/youtrack/issue/codio-8326
> 8325 Delete Homepage banner

- source/features/index.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8339
> 8339 Fixed broken link

- source/404.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8297
> 8297 Updated 404 page

- source/stylesheets/pages/_university.scss
- source/university.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8368
> 8368 quick win changes to university page

- source/index.html.erb
- source/stylesheets/pages/_index.scss
https://codio.myjetbrains.com/youtrack/issue/codio-8387
> 8387 remove banner

- source/index.html.erb
- source/stylesheets/pages/_index.scss
https://codio.myjetbrains.com/youtrack/issue/codio-8433
> Remove CSTA banner and carousel slide controls

- source/partials/_footer.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8407
> 8407 Add Google Adwords to general footer page

- source/features/technicalspecifications.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8550
> 8550 Typos on Technical Specifications page

- source/index.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8761
> Update site metadata description.

- config.rb
- source/features/index.html.erb
- source/index.html.erb
- source/pricing.html.erb
- source/university.html.erb
- source/universityleadership.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8761
> Sitemap update

- config.rb
- source/features/index.html.erb
- source/index.html.erb
- source/pricing.html.erb
- source/university.html.erb
- source/universityleadership.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-8761
> change pages priority in sitemap

- source/docs/index.html.erb
- source/javascripts/partials/_docs.es6
- source/partials/_docs-side-navigation.erb
- source/stylesheets/pages/_docs.scss
- source/stylesheets/partials/_docs-side-navigation.scss
https://codio.myjetbrains.com/youtrack/issue/codio-9085
> 9085 Docs table cf contents improvements

- source/javascripts/partials/_docs.es6
https://codio.myjetbrains.com/youtrack/issue/codio-9208
> 9208 Documentation LH menu

- source/stylesheets/pages/features/_features-subheader.scss
https://codio.myjetbrains.com/youtrack/issue/codio-9075
> 9075 Tiny sites issues

- source/legal/servicelevel.html.md
https://codio.myjetbrains.com/youtrack/issue/codio-9403
> 9403 Update Service agreement page

- source/partials/_head.erb
https://codio.myjetbrains.com/youtrack/issue/codio-9603
> added cookieconsent styles

- source/javascripts/partials/_docs.es6
https://codio.myjetbrains.com/youtrack/issue/codio-9669
> 9669 Search is not working in docs

- config.rb
- source/javascripts/partials/_pricing.es6
see https://codio.myjetbrains.com/youtrack/issue/codio-9689
> Cookieconcent is unavailable

- source/cloudcs.html.erb
- source/developer.html.erb
- source/docs/dashboard/account/billing-ind.html.md
- source/features/content-authoring.html.erb
- source/features/curriculum.html.erb
- source/features/grading.html.erb
- source/features/ide.html.erb
- source/features/infrastructure.html.erb
- source/features/lms.html.erb
- source/features/management.html.erb
- source/features/templates.html.erb
- source/pricing.html.erb
- source/school.html.erb
https://codio.myjetbrains.com/youtrack/issue/codio-9754
> issue #codio-9574. shorten trial period.

- source/cloudcs.html.erb
- source/stylesheets/pages/_cloudcs.scss
https://codio.myjetbrains.com/youtrack/issue/codio-9756
> 9756 CloudCS info should be centered

- source/about/mission.html.erb
- source/stylesheets/pages/_mission.scss
https://codio.myjetbrains.com/youtrack/issue/codio-9776
> 9776 Mission page is broken

- source/partials/_docs-side-navigation.erb
https://codio.myjetbrains.com/youtrack/issue/codio-10334
> 10334 Docs menu
